### ISSUE TITLE
Does not support Python 3.6 ?

### ISSUE THREAD

**Issue by Chanonry** [aronim/serverless-plugin-fastdeploy#1]
FYI

On installation I get trace below. Looks like a gyp issue covered here : https://github.com/nodejs/node-gyp/issues/1337

It's not happy I am running pyton3.6

> @ronomon/base64@2.3.0 install /Users/as/node_modules/@ronomon/base64
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/as/anaconda3/bin/python" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:567:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/as/node_modules/@ronomon/base64
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/andyspence/package.json'
npm WARN as No description
npm WARN as No repository field.
npm WARN as No README data
npm WARN as No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ronomon/base64@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ronomon/base64@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/as/.npm/_logs/2018-08-18T09_14_03_101Z-debug.log

**Comment by kevinsewell** [comment]
Thank you for reporting this. The culprit dependency wasn't even being used :-( I removed @ronomon/base64, so hopefully all should be good now in version 0.0.3

**Comment by Chanonry** [comment]
Excellent, thanks
